### ISSUE TITLE
How do i run it?

### ISSUE THREAD

**Issue by kotik1998** [cheddar-cheeze/recaptcha-solver#1]
Hello there, can you tell me how to run the script and implement on selenium script

**Comment by cheddar-cheeze** [comment]
not finished with it but soon tm

**Comment by cheddar-cheeze** [comment]
i will create a setup guide once i believe its in a well working condition

**Comment by kotik1998** [comment]
Do you have discord? If so can you add me Kot#1883 
Thanks
